// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Antonin Jenik

#pragma once

#include "StrategicRequest.h"

#include <chrono>
#include <cstdint>
#include <filesystem>
#include <vector>

namespace strategic_nexus {

struct RunConfig {
    bool daemonMode = false;
    bool bridgePipelineMode = false;
    bool v0PipelineMode = false;
    bool v0PriorityQueueMode = false;
    bool generatedOverlayCompileMode = false;
    bool generatedOverlayVerifyMode = false;
    bool generatedOverlayPublishMode = false;
    bool archiveStableSavesMode = false;
    bool archiveLiveSavesMode = false;
    bool verifyAutosaveArchiveMode = false;
    bool summarizeAutosaveArchiveMode = false;
    bool buildSeasonDeltaLedgerMode = false;
    bool buildEmpireBriefFromArchiveMode = false;
    bool buildMinistryInputFromArchiveMode = false;
    bool v0PipelineFromArchiveMode = false;
    bool scanSaveCampaignsMode = false;
    bool diffSaveCampaignsMode = false;
    bool planCampaignLibraryMode = false;
    bool compileCampaignLibraryOverlayMode = false;
    bool toggleCampaignLibraryPinMode = false;
    bool discoverStellarisSaveRootsMode = false;
    bool detectStellarisRunningMode = false;
    bool exportMpOverlayPackageMode = false;
    bool verifyMpOverlayPackageMode = false;
    bool importMpOverlayPackageMode = false;
    bool sncStatusSnapshotMode = false;
    bool sncLiveAutosaveMonitorMode = false;
    bool sncSessionCaptureMode = false;
    bool offlineSpineMode = false;
    bool parseStellarisSaveMode = false;
    bool analyzeSaveEntryPointsMode = false;
    bool buildPostPlayPackageMode = false;
    bool buildSncDecisionInputPackageMode = false;
    bool buildSncCandidateDecisionPackageMode = false;
    bool buildSncDslDraftPackageMode = false;
    bool stageSncGeneratedOverlayMode = false;
    bool publishSncGeneratedOverlayMode = false;
    bool prepareLocalLlmModelMode = false;
    bool createSncFriendRequestMode = false;
    bool createSncFriendAcceptanceMode = false;
    bool importSncFriendAcceptanceMode = false;
    bool createSncFriendMpSyncEnvelopeMode = false;
    bool verifySncFriendMpSyncEnvelopeMode = false;
    bool planSncFriendMpSyncInboxMode = false;
    bool planSncFriendMpSyncOutboxMode = false;
    std::filesystem::path exchangeDirectory = "exchange";
    std::chrono::milliseconds daemonPollInterval = std::chrono::milliseconds(1000);
    int daemonMaxIterations = 0;
    std::filesystem::path bridgeDecisionPath;
    std::filesystem::path bridgeEffectBatchPath;
    std::filesystem::path bridgeSequenceStatePath;
    std::int64_t bridgeNowUnixMs = 0;
    std::filesystem::path v0InputContextPath;
    std::filesystem::path v0DecisionOutputPath;
    std::filesystem::path v0AuditOutputPath;
    std::filesystem::path v0PriorityQueueOutputPath;
    std::filesystem::path generatedOverlayDslInputPath;
    std::filesystem::path generatedOverlayOutputDirectory;
    std::filesystem::path generatedOverlayVerifyDirectory;
    std::filesystem::path generatedOverlayPublishStagedDirectory;
    std::filesystem::path generatedOverlayPublishActiveDirectory;
    std::filesystem::path autosaveArchiveSourceRoot;
    std::filesystem::path autosaveArchiveRoot;
    std::filesystem::path autosaveArchiveVerifyDirectory;
    std::filesystem::path autosaveArchiveSummaryDirectory;
    std::filesystem::path autosaveArchiveSummaryOutputPath;
    std::filesystem::path seasonDeltaLedgerDirectory;
    std::filesystem::path seasonDeltaLedgerOutputPath;
    std::filesystem::path archiveEmpireBriefDirectory;
    std::filesystem::path archiveEmpireBriefOutputPath;
    std::filesystem::path archiveMinistryInputDirectory;
    std::filesystem::path archiveMinistryInputOutputPath;
    std::filesystem::path archivePipelineDirectory;
    std::filesystem::path archivePipelineMinistryInputOutputPath;
    std::filesystem::path archivePipelineDecisionOutputPath;
    std::filesystem::path archivePipelineAuditOutputPath;
    std::string archiveMinistryInputCampaignId;
    std::string archivePipelineCampaignId;
    std::string seasonDeltaLedgerCampaignId;
    std::string archiveEmpireBriefCampaignId;
    std::string archiveEmpireBriefEmpireId;
    std::string archiveMinistryInputEmpireId;
    std::string archiveMinistryInputMinistry;
    std::string archivePipelineEmpireId;
    std::string archivePipelineMinistry;
    std::string autosaveArchiveSessionId;
    std::filesystem::path saveCampaignScanRoot;
    std::filesystem::path saveCampaignScanOutputPath;
    std::filesystem::path saveCampaignPreviousRoot;
    std::filesystem::path saveCampaignCurrentRoot;
    std::filesystem::path saveCampaignDiffOutputPath;
    std::filesystem::path campaignLibraryPlanRoot;
    std::filesystem::path campaignLibraryPlanOutputPath;
    std::filesystem::path campaignLibraryPinManifestPath;
    std::filesystem::path campaignLibraryOverlayDslInputPath;
    std::filesystem::path campaignLibraryOverlaySaveRoot;
    std::filesystem::path campaignLibraryOverlayOutputDirectory;
    std::filesystem::path stellarisSaveRootsOutputPath;
    std::filesystem::path stellarisRunningOutputPath;
    std::filesystem::path mpOverlaySourceDirectory;
    std::filesystem::path mpOverlayPackageDirectory;
    std::filesystem::path sncMpOverlayPackageZipPath;
    std::filesystem::path mpOverlayImportTargetDirectory;
    std::filesystem::path sncArchiveRoot;
    std::filesystem::path sncGeneratedOverlayDirectory;
    std::filesystem::path sncStatusOutputPath;
    std::vector<std::filesystem::path> sncLiveAutosaveSaveRoots;
    std::filesystem::path sncLiveAutosaveArchiveRoot;
    std::filesystem::path sncLiveAutosaveStatusOutputPath;
    std::filesystem::path offlineSpineArchiveDirectory;
    std::filesystem::path offlineSpineDslInputPath;
    std::filesystem::path offlineSpineWorkDirectory;
    std::filesystem::path offlineSpineGeneratedOverlayDirectory;
    std::filesystem::path offlineSpineStatusOutputPath;
    std::filesystem::path stellarisSaveParseInputPath;
    std::filesystem::path stellarisSaveParseOutputPath;
    std::filesystem::path saveEntryPointArchiveDirectory;
    std::filesystem::path saveEntryPointAnalysisOutputPath;
    std::vector<std::filesystem::path> saveEntryPointRoots;
    std::filesystem::path postPlayPackageArchiveDirectory;
    std::filesystem::path postPlayPackageOutputPath;
    std::vector<std::filesystem::path> postPlayPackageSaveRoots;
    std::filesystem::path sncDecisionInputPostPlayPackagePath;
    std::filesystem::path sncDecisionInputOutputPath;
    std::filesystem::path sncCandidateDecisionInputPackagePath;
    std::filesystem::path sncCandidateDecisionOutputPath;
    std::filesystem::path sncDslDraftCandidatePackagePath;
    std::filesystem::path sncDslDraftOutputPath;
    std::filesystem::path sncDslDraftAuditOutputPath;
    std::filesystem::path sncGeneratedOverlayDslPath;
    std::filesystem::path sncGeneratedOverlayStagingDirectory;
    std::filesystem::path sncGeneratedOverlayStagingStatusOutputPath;
    std::filesystem::path sncGeneratedOverlayPublishStagingStatusPath;
    std::filesystem::path sncGeneratedOverlayPublishActiveDirectory;
    std::filesystem::path sncGeneratedOverlayPublishStatusOutputPath;
    std::filesystem::path sncGeneratedOverlayPublishBackupRootDirectory;
    std::filesystem::path localLlmPrepareStateOutputPath;
    std::filesystem::path sncFriendRequestOutputPath;
    std::filesystem::path sncFriendRequestInputPath;
    std::filesystem::path sncFriendAcceptanceOutputPath;
    std::filesystem::path sncFriendAcceptanceInputPath;
    std::filesystem::path sncFriendTrustStoreOutputPath;
    std::filesystem::path sncFriendMpSyncEnvelopeOutputPath;
    std::filesystem::path sncFriendMpSyncEnvelopeInputPath;
    std::filesystem::path sncFriendMpSyncEncryptedPayloadInputPath;
    std::string mpOverlayCampaignId;
    std::string mpOverlayOverlayVersion;
    std::string mpOverlayGameVersion;
    std::string mpOverlayStrategicNexusModVersion;
    std::string mpOverlayExpectedCampaignId;
    std::string mpOverlayExpectedOverlayVersion;
    std::string mpOverlayExpectedGameVersion;
    std::string mpOverlayExpectedStrategicNexusModVersion;
    std::string mpOverlayExpectedManifestHash;
    std::string offlineSpineCampaignId;
    std::string offlineSpineEmpireId;
    std::string sncLiveAutosaveSessionId;
    std::string sncGeneratedOverlayOwnerApprovalToken;
    std::string localLlmPrepareModelId;
    std::string localLlmPrepareRuntimeUrl = "http://127.0.0.1:11434";
    std::string sncFriendNodeId;
    std::string sncFriendDisplayName;
    std::string sncFriendSigningPublicKey;
    std::string sncFriendEncryptionPublicKey;
    std::string sncFriendFingerprint;
    std::string sncFriendCreatedAt;
    std::string sncFriendExpiresAt;
    std::string sncFriendAcceptedAt;
    std::string sncFriendLocalAlias;
    std::string sncFriendTrustState;
    std::string sncFriendTrustUpdatedAt;
    bool sncFriendTrustAutoSyncEnabled = false;
    std::string sncFriendRecipientNodeId;
    std::string sncFriendRecipientDisplayName;
    std::string sncFriendRecipientSigningPublicKey;
    std::string sncFriendRecipientEncryptionPublicKey;
    std::string sncFriendRecipientFingerprint;
    std::string sncFriendMpSyncCampaignId;
    std::string sncFriendMpSyncOverlayVersion;
    std::string sncFriendMpSyncPackageManifestHash;
    std::string sncFriendMpSyncPackageZipHash;
    std::string sncFriendMpSyncEncryptedPayloadHash;
    std::string sncFriendMpSyncSigningAlgorithm;
    std::string sncFriendMpSyncEncryptionAlgorithm;
    std::string sncFriendMpSyncSignature;
    std::string sncFriendMpSyncCreatedAt;
    bool mpOverlayPreviousHostAvailable = true;
    bool updateSncFriendTrustStoreEntryMode = false;
    bool sncStartWithWindowsEnabled = false;
    bool sncUseConfiguredStartWithWindowsState = false;
    bool sncUseDetectedStellarisState = true;
    bool sncStellarisRunningOverride = false;
    bool sncLiveAutosaveUseDetectedStellarisState = true;
    bool sncLiveAutosaveStellarisRunningOverride = false;
    bool sncLiveAutosaveCaptureWhenStellarisNotRunning = false;
    bool generatedOverlayPublishStellarisRunning = false;
    bool generatedOverlayPublishUseDetectedStellarisState = true;
    bool sncGeneratedOverlayPublishStellarisRunning = false;
    bool sncGeneratedOverlayPublishUseDetectedStellarisState = true;
    bool sncFriendMpSyncEnvelopeStellarisRunning = false;
    bool sncFriendMpSyncAutoSyncEnabled = false;
    bool localLlmPrepareUserLicenseAccepted = false;
    bool localLlmPrepareAllowDownload = false;
    std::vector<std::filesystem::path> v0PriorityQueueInputPaths;
    std::int64_t v0SequenceId = 1;
    std::int64_t v0CreatedUnixMs = 0;
    std::int64_t v0TtlMs = 30000;
    std::int64_t campaignLibraryMaxCampaigns = 16;
    std::int64_t campaignLibraryOverlayMaxCampaigns = 16;
    std::string campaignLibraryPinCampaignKey;
    std::string campaignLibraryPinTargetState;
    std::int64_t autosaveArchiveStabilityDelayMs = 250;
    std::int64_t sncLiveAutosavePollIntervalMs = 1000;
    std::int64_t sncLiveAutosaveStabilityDelayMs = 250;
    std::int64_t sncLiveAutosaveMaxIterations = 1;
    std::int64_t sncFriendMpSyncEncryptedPayloadBytes = 0;
    StrategicRequest request;
};

class Application {
public:
    int run(const RunConfig& config) const;
};

RunConfig parseRunConfig(int argc, char* argv[]);

} // namespace strategic_nexus

