param(
    [string]$RoadmapFilePath = "docs/DEVELOPMENT_ROADMAP.md",
    [string]$WorkLogPath = ".codex_local/implementation_work_log.csv",
    [string]$OutputPath = "dist/private_reports/roadmap_complexity_estimate.json",
    [bool]$UpdateRoadmapSnapshot = $true
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")

function Resolve-ProjectPath {
    param([string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }
    return Join-Path $repoRoot $Path
}

function Get-StatusProgress {
    param([string]$Status)

    switch ($Status) {
        "DONE" { return 100 }
        "VERIFIED" { return 100 }
        "IMPLEMENTED" { return 100 }
        "IN_PROGRESS" { return 35 }
        "BLOCKED" { return 5 }
        "NOT_STARTED" { return 0 }
        default { return 0 }
    }
}

function Get-RoadmapItemComplexity {
    param(
        [string]$Title,
        [string]$Body
    )

    $requiredBlock = ""
    $requiredMatch = [regex]::Match($Body, "(?ms)^Required:\s*\r?\n(?<required>.*?)(^Notes:|^Current progress:|^Planned requirement:|^---)")
    if ($requiredMatch.Success) {
        $requiredBlock = $requiredMatch.Groups["required"].Value
    }

    $requiredCount = [regex]::Matches($requiredBlock, "(?m)^\s*\*\s+").Count
    $currentProgressCount = [regex]::Matches($Body, "(?m)^Current progress:").Count

    $points = 3 + $requiredCount

    if ($Title -match "(?i)(multiplayer|runtime|memory|personality|empire|orchestrator|overlay distribution)") {
        $points += 4
    }
    if ($Title -match "(?i)(advanced)") {
        $points += 6
    }
    if ($currentProgressCount -gt 0) {
        $points += 1
    }

    return [pscustomobject]@{
        points = [int][Math]::Max(2, [Math]::Min(30, $points))
        required_count = $requiredCount
    }
}

function Get-RemainingEstimate {
    param(
        [double]$RemainingPoints,
        [double]$PointsPerHour
    )

    if ($PointsPerHour -gt 0) {
        $hours = [Math]::Ceiling($RemainingPoints / $PointsPerHour)
        if ($hours -lt 10) {
            return "cca $hours hodin + testovani"
        }
        $weeksLow = [Math]::Max(1, [Math]::Floor($hours / 10))
        $weeksHigh = [Math]::Max($weeksLow + 1, [Math]::Ceiling($hours / 5))
        return "cca $weeksLow-$weeksHigh tydnu podle tempa"
    }

    if ($RemainingPoints -gt 120) { return "6-12 tydnu Freework + testovani" }
    if ($RemainingPoints -gt 80) { return "5-10 tydnu Freework + testovani" }
    if ($RemainingPoints -gt 45) { return "3-7 tydnu Freework + testovani" }
    if ($RemainingPoints -gt 20) { return "2-5 tydnu Freework + testovani" }
    return "1-3 tydny doladeni/testovani"
}

function Get-Percent {
    param(
        [double]$Part,
        [double]$Whole
    )

    if ($Whole -le 0) {
        return 0
    }
    return [int][Math]::Round(($Part / $Whole) * 100.0)
}

function New-RoadmapProgressSnapshotMarkdown {
    param(
        [int]$WeightedProgressPercent,
        [int]$ImplementationCompletePercent,
        [int]$ImplementedComplexityPercent,
        [int]$VerifiedComplexityPercent,
        [int]$ImplementedItemPercent,
        [int]$VerifiedItemPercent,
        [int]$ItemCount,
        [int]$TotalComplexityPoints,
        [double]$CompletedComplexityPoints,
        [double]$RemainingComplexityPoints,
        [string]$RemainingEstimate,
        [string]$Confidence,
        [object[]]$StatusBreakdown
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("<!-- ROADMAP_PROGRESS_SNAPSHOT_START -->")
    $lines.Add("# Roadmap Progress Snapshot")
    $lines.Add("")
    $lines.Add('Auto-generated by `tools/dev_attention/analyze_roadmap_complexity.ps1` from roadmap item statuses and weighted complexity points.')
    $lines.Add("")
    $lines.Add("| Metric | Value |")
    $lines.Add("| --- | ---: |")
    $lines.Add("| Weighted overall progress | $WeightedProgressPercent% |")
    $lines.Add("| Strict implementation complete | $ImplementationCompletePercent% |")
    $lines.Add("| Implemented-or-better complexity | $ImplementedComplexityPercent% |")
    $lines.Add("| Verified-or-done complexity | $VerifiedComplexityPercent% |")
    $lines.Add("| Implemented-or-better items | $ImplementedItemPercent% |")
    $lines.Add("| Verified-or-done items | $VerifiedItemPercent% |")
    $lines.Add("| Roadmap items | $ItemCount |")
    $lines.Add("| Complexity points | $TotalComplexityPoints |")
    $lines.Add("| Completed weighted points | $([Math]::Round($CompletedComplexityPoints, 2)) |")
    $lines.Add("| Remaining weighted points | $([Math]::Round($RemainingComplexityPoints, 2)) |")
    $lines.Add("| Remaining estimate | $RemainingEstimate |")
    $lines.Add("| Estimate confidence | $Confidence |")
    $lines.Add("")
    $lines.Add("| Status | Items | Complexity points | Complexity share | Weighted completed points |")
    $lines.Add("| --- | ---: | ---: | ---: | ---: |")
    foreach ($row in $StatusBreakdown) {
        $lines.Add("| $($row.status) | $($row.item_count) | $($row.complexity_points) | $($row.complexity_percent)% | $($row.completed_points) |")
    }
    $lines.Add("<!-- ROADMAP_PROGRESS_SNAPSHOT_END -->")
    return ($lines -join [Environment]::NewLine)
}

function Update-RoadmapProgressSnapshot {
    param(
        [string]$RoadmapPath,
        [string]$SnapshotMarkdown
    )

    $roadmapText = Get-Content -Raw -LiteralPath $RoadmapPath
    $snapshotPattern = "(?ms)<!-- ROADMAP_PROGRESS_SNAPSHOT_START -->.*?<!-- ROADMAP_PROGRESS_SNAPSHOT_END -->"

    if ([regex]::IsMatch($roadmapText, $snapshotPattern)) {
        $updated = [regex]::Replace($roadmapText, $snapshotPattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $SnapshotMarkdown }, 1)
    } else {
        $insertPattern = "(?m)^---\s*$"
        $insertMatch = [regex]::Match($roadmapText, $insertPattern)
        if (-not $insertMatch.Success) {
            throw "Roadmap progress snapshot markers are missing and no insertion point was found."
        }
        $insertAt = $insertMatch.Index + $insertMatch.Length
        $updated = $roadmapText.Substring(0, $insertAt) +
            [Environment]::NewLine + [Environment]::NewLine +
            $SnapshotMarkdown +
            [Environment]::NewLine + [Environment]::NewLine +
            $roadmapText.Substring($insertAt)
    }

    $bytes = [System.IO.File]::ReadAllBytes($RoadmapPath)
    $hasUtf8Bom = $bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF
    if ($updated -ne $roadmapText -or $hasUtf8Bom) {
        [System.IO.File]::WriteAllText(
            $RoadmapPath,
            $updated,
            [System.Text.UTF8Encoding]::new($false))
    }
}

$roadmapPath = Resolve-ProjectPath $RoadmapFilePath
$workLogResolvedPath = Resolve-ProjectPath $WorkLogPath
$outputResolvedPath = Resolve-ProjectPath $OutputPath

if (-not (Test-Path -LiteralPath $roadmapPath)) {
    throw "Roadmap file not found: $roadmapPath"
}

$text = Get-Content -Raw -LiteralPath $roadmapPath
$matches = [regex]::Matches(
    $text,
    "(?ms)^##\s+(?<number>[0-9]+[A-Z]?)\.\s+(?<title>[^\r\n]+)(?<body>.*?)(?=^##\s+[0-9]+[A-Z]?\.\s+|\z)")

$items = @()
$totalPoints = 0.0
$donePoints = 0.0
$statusCounts = @{}
$statusPoints = @{}
$statusDonePoints = @{}
$implementedStatuses = @("IMPLEMENTED", "VERIFIED", "DONE")
$verifiedStatuses = @("VERIFIED", "DONE")

foreach ($match in $matches) {
    $title = [string]$match.Groups["title"].Value
    $body = [string]$match.Groups["body"].Value
    $statusMatch = [regex]::Match($body, "(?m)^Status:\s*\r?\n(?<status>[A-Z_]+)")
    if (-not $statusMatch.Success) {
        continue
    }

    $status = [string]$statusMatch.Groups["status"].Value
    $progress = Get-StatusProgress -Status $status
    $complexity = Get-RoadmapItemComplexity -Title $title -Body $body
    $points = [double]$complexity.points
    $done = $points * ($progress / 100.0)

    $totalPoints += $points
    $donePoints += $done
    if (-not $statusCounts.ContainsKey($status)) {
        $statusCounts[$status] = 0
    }
    $statusCounts[$status]++
    if (-not $statusPoints.ContainsKey($status)) {
        $statusPoints[$status] = 0.0
    }
    $statusPoints[$status] += $points
    if (-not $statusDonePoints.ContainsKey($status)) {
        $statusDonePoints[$status] = 0.0
    }
    $statusDonePoints[$status] += $done

    $items += [pscustomobject]@{
        id = [string]$match.Groups["number"].Value
        title = $title
        status = $status
        status_progress_percent = $progress
        implemented = ($implementedStatuses -contains $status)
        verified = ($verifiedStatuses -contains $status)
        complexity_points = [int]$points
        completed_points = [Math]::Round($done, 2)
        required_count = $complexity.required_count
    }
}

if ($totalPoints -le 0) {
    throw "No analyzable roadmap items found."
}

$loggedRows = @()
if (Test-Path -LiteralPath $workLogResolvedPath) {
    $loggedRows = @(Import-Csv -LiteralPath $workLogResolvedPath | Where-Object {
        $_.duration_minutes -and $_.complexity_points_done -and [double]$_.duration_minutes -gt 0 -and [double]$_.complexity_points_done -gt 0
    })
}

$loggedMinutes = 0.0
$loggedPoints = 0.0
foreach ($row in $loggedRows) {
    $loggedMinutes += [double]$row.duration_minutes
    $loggedPoints += [double]$row.complexity_points_done
}

$pointsPerHour = 0.0
if ($loggedMinutes -gt 0) {
    $pointsPerHour = $loggedPoints / ($loggedMinutes / 60.0)
}

$percent = [int][Math]::Round(($donePoints / $totalPoints) * 100.0)
$remainingPoints = [Math]::Max(0, $totalPoints - $donePoints)
$statusSummary = (($statusCounts.GetEnumerator() | Sort-Object Name | ForEach-Object { "$($_.Key)=$($_.Value)" }) -join ", ")
$confidence = if ($loggedRows.Count -ge 5) { "stredni" } else { "nizka" }
$statusOrder = @("DONE", "VERIFIED", "IMPLEMENTED", "IN_PROGRESS", "BLOCKED", "NOT_STARTED")
$allStatuses = @($statusOrder + @($statusCounts.Keys | Where-Object { $statusOrder -notcontains $_ } | Sort-Object))
$statusBreakdown = @()
foreach ($statusName in $allStatuses) {
    $count = if ($statusCounts.ContainsKey($statusName)) { [int]$statusCounts[$statusName] } else { 0 }
    $pointsForStatus = if ($statusPoints.ContainsKey($statusName)) { [double]$statusPoints[$statusName] } else { 0.0 }
    $doneForStatus = if ($statusDonePoints.ContainsKey($statusName)) { [double]$statusDonePoints[$statusName] } else { 0.0 }
    $statusBreakdown += [pscustomobject]@{
        status = $statusName
        item_count = $count
        item_percent = Get-Percent -Part $count -Whole $items.Count
        complexity_points = [int][Math]::Round($pointsForStatus)
        complexity_percent = Get-Percent -Part $pointsForStatus -Whole $totalPoints
        completed_points = [Math]::Round($doneForStatus, 2)
    }
}

$implementedPoints = ($items | Where-Object { $_.implemented } | Measure-Object -Property complexity_points -Sum).Sum
$verifiedPoints = ($items | Where-Object { $_.verified } | Measure-Object -Property complexity_points -Sum).Sum
$implementedItemCount = @($items | Where-Object { $_.implemented }).Count
$verifiedItemCount = @($items | Where-Object { $_.verified }).Count
$implementedComplexityPercent = Get-Percent -Part ([double]$implementedPoints) -Whole $totalPoints
$verifiedComplexityPercent = Get-Percent -Part ([double]$verifiedPoints) -Whole $totalPoints
$implementationCompletePercent = $implementedComplexityPercent
$implementationOpenPoints = [Math]::Max(0, $totalPoints - [double]$implementedPoints)
$implementedItemPercent = Get-Percent -Part $implementedItemCount -Whole $items.Count
$verifiedItemPercent = Get-Percent -Part $verifiedItemCount -Whole $items.Count
$remainingEstimate = Get-RemainingEstimate -RemainingPoints $remainingPoints -PointsPerHour $pointsPerHour
$inProgressRow = $statusBreakdown | Where-Object { $_.status -eq "IN_PROGRESS" } | Select-Object -First 1
$inProgressComplexityPercent = if ($null -ne $inProgressRow) { [int]$inProgressRow.complexity_percent } else { 0 }
$inProgressComplexityPoints = if ($null -ne $inProgressRow) { [int]$inProgressRow.complexity_points } else { 0 }
$implementationPrecisionNote = "Strict implementation percent counts only roadmap complexity with IMPLEMENTED, VERIFIED, or DONE status. Weighted overall progress also credits IN_PROGRESS/BLOCKED partial status and is a forecast-style progress signal, not hard completion."

$directory = Split-Path -Parent $outputResolvedPath
if ($directory -and -not (Test-Path -LiteralPath $directory)) {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
}

$outputJson = [pscustomobject]@{
    schema_version = 1
    updated_at = (Get-Date).ToString("o")
    percent = $percent
    weighted_progress_percent = $percent
    implementation_complete_percent = $implementationCompletePercent
    implementation_open_percent = Get-Percent -Part $implementationOpenPoints -Whole $totalPoints
    implementation_open_complexity_points = [Math]::Round($implementationOpenPoints, 2)
    in_progress_complexity_percent = $inProgressComplexityPercent
    in_progress_complexity_points = $inProgressComplexityPoints
    verification_complete_percent = $verifiedComplexityPercent
    implemented_percent = $implementedComplexityPercent
    verified_percent = $verifiedComplexityPercent
    implemented_item_percent = $implementedItemPercent
    verified_item_percent = $verifiedItemPercent
    remaining = $remainingEstimate
    confidence = $confidence
    basis = "automaticky vazeny odhad: $([int]$totalPoints) bodu roadmapy, $([Math]::Round($donePoints, 1)) vazene hotovo, $([Math]::Round($remainingPoints, 1)) zbyva; striktne implementovano=$implementationCompletePercent%, overeno=$verifiedComplexityPercent%, rozpracovano=$inProgressComplexityPercent%; $statusSummary"
    implementation_basis = $implementationPrecisionNote
    item_count = $items.Count
    total_complexity_points = [int]$totalPoints
    completed_complexity_points = [Math]::Round($donePoints, 2)
    remaining_complexity_points = [Math]::Round($remainingPoints, 2)
    implemented_complexity_points = [Math]::Round([double]$implementedPoints, 2)
    verified_complexity_points = [Math]::Round([double]$verifiedPoints, 2)
    implemented_item_count = $implementedItemCount
    verified_item_count = $verifiedItemCount
    status_breakdown = @($statusBreakdown)
    logged_work_rows = $loggedRows.Count
    logged_minutes = [int][Math]::Round($loggedMinutes)
    logged_points_done = [Math]::Round($loggedPoints, 2)
    points_per_hour = [Math]::Round($pointsPerHour, 2)
    owner_summary = "implementace $implementationCompletePercent% | postup $percent% | overeno $verifiedComplexityPercent%"
    items = @($items)
} | ConvertTo-Json -Depth 8

[System.IO.File]::WriteAllText(
    $outputResolvedPath,
    $outputJson + [Environment]::NewLine,
    [System.Text.UTF8Encoding]::new($false))

if ($UpdateRoadmapSnapshot) {
    $snapshotMarkdown = New-RoadmapProgressSnapshotMarkdown `
        -WeightedProgressPercent $percent `
        -ImplementationCompletePercent $implementationCompletePercent `
        -ImplementedComplexityPercent $implementedComplexityPercent `
        -VerifiedComplexityPercent $verifiedComplexityPercent `
        -ImplementedItemPercent $implementedItemPercent `
        -VerifiedItemPercent $verifiedItemPercent `
        -ItemCount $items.Count `
        -TotalComplexityPoints ([int]$totalPoints) `
        -CompletedComplexityPoints $donePoints `
        -RemainingComplexityPoints $remainingPoints `
        -RemainingEstimate $remainingEstimate `
        -Confidence $confidence `
        -StatusBreakdown $statusBreakdown

    Update-RoadmapProgressSnapshot -RoadmapPath $roadmapPath -SnapshotMarkdown $snapshotMarkdown
}

Write-Host "roadmap_complexity_estimate_written=$outputResolvedPath"
Write-Host "roadmap_progress_percent=$percent"
Write-Host "roadmap_implemented_percent=$implementedComplexityPercent"
Write-Host "roadmap_verified_percent=$verifiedComplexityPercent"
Write-Host "roadmap_complexity_points=$([int]$totalPoints)"
